// <auto-generated />
using System;
using AgriculturalResourceManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgriculturalResourceManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Categories", b =>
                {
                    b.Property<string>("status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("inforesult_coverage")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("status");

                    b.HasIndex("inforesult_coverage");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Category", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categoriesstatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sequence")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Categoriesstatus");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Info", b =>
                {
                    b.Property<string>("result_coverage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("timingexecuting")
                        .HasColumnType("int");

                    b.Property<int?>("totalrecord_count")
                        .HasColumnType("int");

                    b.HasKey("result_coverage");

                    b.HasIndex("timingexecuting");

                    b.HasIndex("totalrecord_count");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reportsstatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Reportsstatus");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Reports", b =>
                {
                    b.Property<string>("status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("inforesult_coverage")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("status");

                    b.HasIndex("inforesult_coverage");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.State", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Statesstatus")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Statesstatus");

                    b.ToTable("State");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.States", b =>
                {
                    b.Property<string>("status")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("inforesult_coverage")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("status");

                    b.HasIndex("inforesult_coverage");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Timing", b =>
                {
                    b.Property<int>("executing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("executing");

                    b.ToTable("Timing");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Total", b =>
                {
                    b.Property<int>("record_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("record_count");

                    b.ToTable("Total");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Categories", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Info", "info")
                        .WithMany()
                        .HasForeignKey("inforesult_coverage");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Category", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Categories", null)
                        .WithMany("data")
                        .HasForeignKey("Categoriesstatus");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Info", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Timing", "timing")
                        .WithMany()
                        .HasForeignKey("timingexecuting");

                    b.HasOne("AgriculturalResourceManagement.Models.Total", "total")
                        .WithMany()
                        .HasForeignKey("totalrecord_count");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Report", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Reports", null)
                        .WithMany("data")
                        .HasForeignKey("Reportsstatus");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.Reports", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Info", "info")
                        .WithMany()
                        .HasForeignKey("inforesult_coverage");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.State", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.States", null)
                        .WithMany("data")
                        .HasForeignKey("Statesstatus");
                });

            modelBuilder.Entity("AgriculturalResourceManagement.Models.States", b =>
                {
                    b.HasOne("AgriculturalResourceManagement.Models.Info", "info")
                        .WithMany()
                        .HasForeignKey("inforesult_coverage");
                });
#pragma warning restore 612, 618
        }
    }
}
